In [1]:
import numpy as np # для работы с массивами
import pandas as pd # для работы DataFrame 
import seaborn as sns # библиотека для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

%matplotlib inline

In [3]:
df = pd.read_csv('Admission_Predict_Ver1.1.csv')


In [111]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [130]:
df_res1 = df[df['Research'] == 0]

In [131]:
TOEFL = df_res1[['TOEFL Score']]
CGPA = df_res1[['CGPA']]
target = df_res1[['Chance of Admit ']]

In [132]:
TOEFL_centr = TOEFL - TOEFL.mean()
CGPA_centr = CGPA - CGPA.mean()
target_centr = target - target.mean()

TOEFL_std = TOEFL_centr / np.linalg.norm(TOEFL_centr)
CGPA_std = CGPA_centr / np.linalg.norm(CGPA_centr)
target_std = target_centr / np.linalg.norm(target_centr)

In [133]:
A = np.column_stack((TOEFL_std, CGPA_std))

In [134]:
A.shape

(220, 2)

In [135]:
np.linalg.lstsq(A, target_std, rcond=None)

(array([[0.19044768],
        [0.62001517]]),
 array([0.41476017]),
 2,
 array([1.30260267, 0.55065986]))

In [147]:
np.array((1, 2, 3)).T @ np.array(([1, 0, 0], [0, 0, -1], [0, 1, 0]))

array([ 1,  3, -2])

In [148]:
np.array((1, -1)).T @ np.array(([2, 1], [1, 2]))

array([ 1, -1])

In [161]:
np.array((1, 1)) @ (np.array(([2, 1], [1, 2]))).T

array([3, 3])

In [151]:
np.array((1, 0)).T @ np.array(([2, 1], [1, 2]))

array([2, 1])

In [156]:
np.array((5, -5)).T @ np.array(([2, 1], [1, 2]))

array([ 5, -5])

In [157]:
np.array((1, -1)) @ np.array((1, 1))

0